# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: lsba-ns-prod
# namePrefix: prod-

# resources:
#   - ../../base

# patches:
#   - target:
#       kind: Namespace
#     patch: |-
#       - op: replace
#         path: /metadata/name
#         value: lsba-ns-prod

#   - target:
#       kind: PersistentVolume
#       name: lsba-pv
#     patch: |-
#       - op: replace
#         path: /spec/claimRef/namespace
#         value: lsba-prod
#       - op: replace
#         path: /spec/claimRef/name
#         value: prod-lsba-pvc
#       - op: replace
#         path: /spec/hostPath/path
#         value: /mnt/volumes/loup-solitaire-book-analyser/prod
#       - op: replace
#         path: /spec/storageClassName
#         value: prod-lsba-sc

#   - target:
#       kind: PersistentVolumeClaim
#       name: lsba-pvc
#     patch: |-
#       - op: replace
#         path: /spec/storageClassName
#         value: prod-lsba-sc
