# attention, stg et prod ne sont pas du tout fait, il faut reprendre à partir de dev et faire les ajustements nécessaires pour stg et prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lsba-ns-prod
nameSuffix: -prod

resources:
  - ../../base
  - lsba-secret-postgresql-credentials.yaml

patches:
  - path: patch-lsba-find-books-cronjob.yaml
  - path: patch-lsba-find-prices-cronjob.yaml
  - path: patch-lsba-pvc.yaml
  - path: patch-lsba-secrets.yaml
        

