apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-books-cronjob
  namespace: lsba-ns
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc-prod