apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-prices-cronjob
  namespace: lsba-ns
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: lsba-sa-no-access-prod
          securityContext:
              fsGroup: 4200
              runAsGroup: 4200
              runAsUser: 4201
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc-prod