"""create book author and price tables

Revision ID: d668c8781f0c
Revises:
Create Date: 2026-07-13 17:16:49.083723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d668c8781f0c"
down_revision: Union[str, Sequence[str], None] = "3551992da1e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("isbn", sa.String(length=13), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("titre", sa.Unicode(length=200), nullable=False),
        sa.Column("last_parution_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Unicode(length=4000), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.Column("image", sa.Unicode(length=500), nullable=False),
        sa.Column("acquired", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_table(
        "book_author",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("book_id", "author_id"),
    )
    op.create_table(
        "book_price",
        sa.Column("isbn", sa.String(length=13), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(["isbn"], ["book.isbn"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("isbn", "source", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_price")
    op.drop_table("book_author")
    op.drop_table("book")
    op.drop_table("author")
    # ### end Alembic commands ###
