apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-books-cronjob
  namespace: lsba-ns
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: lsba-sa-noright-stg
          securityContext:
              fsGroup: 4100
              runAsGroup: 4100
              runAsUser: 4101
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc-stg