apiVersion: v1
kind: ConfigMap
metadata:
  name: loup-solitaire-book-analyser-cm
data:
  CONNECTION_STRING: tomes.data.json
  FILE_SYSTEM_PATH: /app/data
  LOG_FILE: /app/logs/app.log
  LOG_LEVEL: INFO
