apiVersion: v1
kind: ConfigMap
metadata:
  name: lsba-cm # patched by overlay
  namespace: lsba-ns # patched by overlay
data:
  # not necessary -> ROOT_DIR: /app
  API_TIMEOUT: "1.0"
  API_PARALLEL_CALLS: "6"
  CONNECTION_STRING: data/tomes.data.json
  LOG_FILE: logs/app.log
  LOG_LEVEL: INFO
