apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-books-cronjob
  namespace: lsba-ns # patched by overlay
spec:
  # attention, le temps est en zoulu time en dev (docker-desktop) !
  schedule: "5 22 * * *" # tous les jours à minuit:05 (UTC+02)
  jobTemplate:
    metadata:
      name: lsba-find-books-job
    spec:
      backoffLimit: 2 # 2 tentatives max en cas d'echec
      template:
        metadata: {}
        spec:
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc # patched by overlay
          containers:
            - image: loup-solitaire-book-analyser:v0.1.2
              name: lsba-find-books
              args: ["src/find_books.py"]
              envFrom:
                - configMapRef:
                    name: lsba-cm
                    optional: false
              volumeMounts:
                - name: project-volume
                  mountPath: /app/data
                  subPath: data
                - name: project-volume
                  mountPath: /app/logs
                  subPath: logs
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "100m"
                requests:
                  memory: "64Mi"
                  cpu: "50m"
          restartPolicy: Never # on veut un nouveau pod en cas d'echec pour analyser les erreurs (tous les logs ne vont pas forcément dans les fichers logs du PVC)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-prices-cronjob
  namespace: lsba-ns # patched by overlay
spec:
  schedule: "7 22 * * *" # chaque jour à 00:07 UTC+02 (soit deux minutes après find_books - histoire de conserver la logique)
  jobTemplate:
    metadata:
      name: lsba-find-prices-job
    spec:
      backoffLimit: 2 # 2 tentatives max en cas d'echec
      template:
        metadata: {}
        spec:
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc # patched by overlay
          containers:
            - image: loup-solitaire-book-analyser:v0.1.2
              name: lsba-find-prices
              args: ["src/find_prices.py"]
              envFrom:
                - configMapRef:
                    name: lsba-cm
                    optional: false
              volumeMounts:
                - name: project-volume
                  mountPath: /app/data
                  subPath: data
                - name: project-volume
                  mountPath: /app/logs
                  subPath: logs
              resources:
                limits:
                  # playwright semble au max avoir besoin de ~800Mi de mémoire et ~1.6 de cpu
                  memory: "1Gi"
                  cpu: "2"
                requests:
                  # playwright necessite au moins 500Mi de mémoire et ~0.5 cpu au min
                  memory: "500Mi"
                  cpu: "0.5"
          restartPolicy: Never # on veut un nouveau pod en cas d'echec pour analyser les erreurs (tous les logs ne vont pas forcément dans les fichers logs du PVC)
