apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - lsba-cm.yaml
  - lsba-find-books-cronjob.yaml
  - lsba-find-books-job.yaml
  - lsba-find-prices-cronjob.yaml
  - lsba-find-prices-job.yaml
  - lsba-ns.yaml
  - lsba-pv.yaml
  - lsba-pvc.yaml
  - lsba-sc.yaml
