apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsba-pvc
  namespace: lsba-ns
spec:
  storageClassName: lsba-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
