apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lsba-sc # patched by overlay
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer # recommandé pour no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lsba-pv # patched by overlay
spec:
  storageClassName: lsba-sc # patched by overlay
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Mi
  hostPath:
    path: /mnt/volumes/lsba/dev
  claimRef:
    name: lsba-pvc # patched by overlay
    namespace: lsba-ns # patched by overlay
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsba-pvc
  namespace: lsba-ns # patched by overlay
spec:
  storageClassName: lsba-sc # patched by overlay
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
