global:
  postgresql:
    auth:
      # Use existing secret instead of generating password
      existingSecret: "lsba-secret-postgresql-credentials"
      secretKeys:
        adminPasswordKey: "postgres-password" # should be updated by the CD pipeline to a strong password 
        userPasswordKey: "password" # should be updated by the CD pipeline to a strong password 
        replicationPasswordKey: "replication-password" # should be updated by the CD pipeline to a strong password

auth:
  # Maintenance user and database created by Bitnami at first startup.
  database: "lsba_db"
  username: "db_migration_usr"

postgresqlDataDir: /app/postgresql/data
primary:  
  # Persistent storage
  persistence:
    enabled: true
    existingClaim: "lsba-pvc-dev"
    size: 10Mi
    # Access mode
    accessModes:
      - ReadWriteMany # un seule PV pour tous les pods mais permissions distincte entre les pods
    mountPath: /app/postgresql
    subPath: postgresql
  
  # Security context  
  podSecurityContext:
    enabled: true
    fsGroup: 4002
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 4000
    runAsGroup: 4002
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"

  # Resource allocation
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 2000m

  # Network policy
  networkPolicy:
    enabled: true
    allowExternal: false
    ingressNSMatchLabels:
      postgres-access: "true"

  # Pod disruption budget
  pdb:
    create: true
    minAvailable: 1 # always keep at least 1 pod available

  # Liveness and readiness probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  
  # Init scripts
  initdb:
    scriptsSecret: lsba-db-scripts
