apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lsba-ns-dev
nameSuffix: -dev

resources:
  - ../../base

patches:
  - path: patch-lsba-find-books-cronjob.yaml
  - path: patch-lsba-find-books-job.yaml
  - path: patch-lsba-find-prices-cronjob.yaml
  - path: patch-lsba-find-prices-job.yaml
  - path: patch-lsba-pv.yaml
  - path: patch-lsba-pvc.yaml
        

