# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: lsba-ns-dev
# nameSuffix: -dev

# resources:
#   - ../../base

# patches:
#   - target:
#       kind: Namespace
#     patch: |-
#       - op: replace
#         path: /metadata/name
#         value: lsba-ns-dev
#   - target:
#       kind: PersistentVolume
#       name: lsba-pv
#     patch: |-
#       - op: replace
#         path: /spec/claimRef/namespace
#         value: lsba-dev
#       - op: replace
#         path: /spec/claimRef/name
#         value: dev-lsba-pvc
#       - op: replace
#         path: /spec/hostPath/path
#         value: /mnt/volumes/loup-solitaire-book-analyser/dev
#       - op: replace
#         path: /spec/storageClassName
#         value: lsba-sc-dev

#   - target:
#       kind: PersistentVolumeClaim
#       name: lsba-pvc
#     patch: |-
#       - op: replace
#         path: /spec/storageClassName
#         value: lsba-sc-dev
