apiVersion: v1
kind: Secret
metadata:
  name: lsba-postgresql-credentials
  namespace: lsba-ns
data:
  password: cGFzc3dvcmQ=
  postgres-password: cG9zdGdyZXMtcGFzc3dvcmQ=
  replication-password: cmVwbGljYXRpb24tcGFzc3dvcmQ=
