apiVersion: v1
kind: Secret
metadata:
  name: lsba-secret-postgresql-credentials
  namespace: lsba-ns
data:
  postgres_pwd_key: cG9zdGdyZXNfcHdkCg==
  db_migration_usr_pwd_key: ZGJfbWlncmF0aW9uX3Vzcl9wd2QK
  db_replication_usr_pwd_key: ZGJfcmVwbGljYXRpb25fdXNyX3B3ZAo=
