apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsba-find-prices-cronjob
  namespace: lsba-ns
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: lsba-sa-no-access-dev
          volumes:
            - name: project-volume
              persistentVolumeClaim:
                claimName: lsba-pvc-dev