apiVersion: v1
kind: Secret
metadata:
  name: lsba-secrets
data:
  CONNECTION_STRING_BATCH: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZGJfYmF0Y2hfdXNyOmRiX2JhdGNoX3Vzcl9wd2RAbHNiYS1kYi1wb3N0Z3Jlc3FsLWRldi5sc2JhLW5zLWRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2xzYmFfZGI=
  CONNECTION_STRING_WEBAPP: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZGJfYmF0Y2hfdXNyOmRiX2JhdGNoX3Vzcl9wd2RAbHNiYS1kYi1wb3N0Z3Jlc3FsLWRldi5sc2JhLW5zLWRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2xzYmFfZGI=
