apiVersion: v1
kind: Secret
metadata:
  name: lsba-secrets
data:
  CONNECTION_STRING_BATCH: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZGJfYmF0Y2hfdXNyOmRiX2JhdGNoX3Vzcl9wd2RAbG9jYWxob3N0OjU0MzIvbHNiYV9kYg==
  CONNECTION_STRING_WEBAPP: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZGJfd2ViYXBwX3VzcjpkYl93ZWJhcHBfdXNyX3B3ZEBsb2NhbGhvc3Q6NTQzMi9sc2JhX2Ri
