apiVersion: batch/v1
kind: Job
metadata:
  name: lsba-find-books-job
  namespace: lsba-ns
spec:
  template:
    spec:
      serviceAccountName: lsba-sa-noright-dev
      volumes:
        - name: project-volume
          persistentVolumeClaim:
            claimName: lsba-pvc-dev